### ISSUE TITLE
Instructions on linkedin.message template

### ISSUE THREAD

**Issue by alphomeg** [joshiayush/inb#49]
Hi,
Please provide the instructions on how to use the linkedin.message? Also are there any plans on implementing the bulk send messages to connections?

**Comment by joshiayush** [comment]
> Please provide the instructions on how to use the linkedin.message?

It is currently impossible to use that feature because I don't have time to include the `message` API to parse the template given by the user and to send that message to the _Note Box_.

https://github.com/joshiayush/inb/blob/9ba97413c53c972092aea43175fae321537f6cb9/inb/linkedin/connect/linkedinsearchconnect.py#L803-L812

In case you are interested then you can create a PR implementing that feature you just have to target the _Add Note_ button and then the _Note_ dialog box will appear and then you just have to send the message to that dialog and hit _Send_.

> Also are there any plans on implementing the bulk send messages to connections?

Not right now, if you are interested then you can create a PR. I'm marking this issue as a feature request :+1: .
