### ISSUE TITLE
Why should we use `LIST` parameters?

### ISSUE THREAD

**Issue by ologbonowiwi** [joshiayush/inb#57]
It is unclear how to use parameters like `--regions` or `--industries`.

Can we provide better docs on this?

**Comment by joshiayush** [comment]
Yes @ologbonowiwi  you are right addressing this issue does not only require to update the docs but to update the interface as well because the `list` type I'm using here:

https://github.com/joshiayush/inb/blob/ed10cb06796883cbbefb6e0d60891713e47bdcc8/inb/inb.py#L64-L67

Splits up each character of the string given to it which is not the desired behaviour we need to change these `list` types to "Multiple Options" as described [here](https://click.palletsprojects.com/en/8.1.x/options/#multiple-options) which is going to be an easy task as it's just to replace the statement `type=list` with `multiple=True` and the rest will be handled by the functions automatically. And once this change has been made you can update the documents as well
