### ISSUE TITLE
Could we have keywords as a multiple parameter?

### ISSUE THREAD

**Issue by ologbonowiwi** [joshiayush/inb#61]
I noticed that keywords could be something we can use with multiple values.

For example, if I want to reach out to recruiters, I could use the following:

```--keywords "Tech Recruiter" --keywords "Recruiter" --keywords "Talent Acquisition"```

What do you think?

**Comment by joshiayush** [comment]
But then I'm not sure how to use that here:

https://github.com/joshiayush/inb/blob/1df542c780e29ffc0c9058f952ea2fab3f869366/inb/api/linkedin_api.py#L301

because I still don't know if LinkedIn Voyager API can handle list type `keywords` parameter or not but if you want to search for multiple keywords then for now you just have to separate them either using "," or "|" symbol, for example:

```
--keywords "Software Engineer, Software Tester, Machine Learning Engineer, Artificial Intelligence Engineer"
```

**Comment by ologbonowiwi** [comment]
Agreed!

Thanks for your response.
