### ISSUE TITLE
Linux issue

### ISSUE THREAD

**Issue by rawathemant246** [joshiayush/inb#66]
I have also tried this package in Linux but it failed to give me any output 
i have tried in ubuntu 20.4  and when i run this script 

python3 inb.py search --email ---xxxxx@gmail.com--password --xxxxx  --keyword 'Software Engineer' --refresh-cookies

Still this  script not giving any errors !!!

kindly resolve the issue

**Comment by joshiayush** [comment]
Are you putting the dashes (-) before the value of the keyword argument also? Because, if yes, then keep in mind that they are not meant to be given like that. Every string passed with double dashes to the program are treated as arguments only not the value.

See [these](https://github.com/joshiayush/inb/blob/main/inb/inb.py#L51-L112) are the currently supported arguments to `inb`.

**Comment by joshiayush** [comment]
@rawathemant246 Sorry for answering so late. I just saw the issues you've created here.

**Comment by joshiayush** [comment]
Closing as stale!
